title = "UILib"                                       # From Git
gitRepoUrl = "https://github.com/ukuroks-games/UILib" # From Git

gitSourceBranch = "master"
changelog = true
classOrder = []

includeReadme = true

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "no"

# From git:
organizationName = "Ukuroks Games"
projectName = "UILib"
url = "https://ukuroks-games.github.io/"
baseUrl = "/UILib"
tagline = ""

[footer]
style = "dark"
copyright = "Copyright © 2025 Egor00f. Built with Moonwave and Docusaurus"
