local DropDownList = require(script.DropDownList)
local bar = require(script.bar)
local checkbox = require(script.checkbox)
local defaultSwitch = require(script.defaultSwitch)
local slider = require(script.slider)
local smoothBar = require(script.smoothBar)
local switch = require(script.switch)
local tabs = require(script.tabs)

return {
	bar = bar,
	smoothBar = smoothBar,
	switch = switch,
	DropDownList = DropDownList,
	checkbox = checkbox,
	defaultSwitch = defaultSwitch,
	tabs = tabs,
	slider = slider
}
